import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {SecurityOperations,withAuditContext} from '../security-operations.mjs';
function fixture(t){const db=new DatabaseSync(':memory:');t.after(()=>db.close());db.exec(`CREATE TABLE audit(id INTEGER PRIMARY KEY,timestamp TEXT,actor_username TEXT,action TEXT,target_username TEXT,details TEXT); CREATE TABLE sessions(id_hash TEXT PRIMARY KEY,user_id TEXT,csrf TEXT,expires INTEGER); CREATE TABLE attempts(key TEXT PRIMARY KEY,count INTEGER,until_at INTEGER); CREATE TABLE users(id TEXT PRIMARY KEY,username TEXT,display_name TEXT,password_hash TEXT,role TEXT,active INTEGER,must_change INTEGER);`);const records=[];let now=Date.now();const operations=new SecurityOperations(db,{logger:event=>records.push(event),clock:()=>now});return {db,operations,records,advance:ms=>{now+=ms;}};}
test('audit records context, redacts sensitive fields and prevents log line injection',t=>{const {db,operations,records}=fixture(t);withAuditContext({ip:'127.0.0.1',correlationId:'synthetic-context',userAgent:'test\nagent'},()=>operations.audit('editor','autorizacion_denegada','synthetic',{password:'private',csrfToken:'private',mfaSecret:'private',path:'safe\nmarker'}));const e=records[0];assert.equal(e.type,'cms_audit');assert.equal(e.context.correlationId,'synthetic-context');assert.equal(e.details.password,'[REDACTED]');assert(!JSON.stringify(e).includes('private'));assert.equal(e.context.userAgent,'test agent');assert.equal(db.prepare('SELECT count(*) AS n FROM audit').get().n,1);});
test('repeated rejection emits deduplicated alert outside audit table',t=>{const {operations,records}=fixture(t);withAuditContext({ip:'127.0.0.1'},()=>{for(let i=0;i<6;i++)operations.audit('access','inicio_fallido','synthetic');});assert.equal(operations.alerts().length,1);assert(records.some(e=>e.type==='cms_security_alert'));const alert=operations.alerts()[0];assert.equal(operations.acknowledge(alert.id,'synthetic_admin').ok,true);assert(operations.alerts()[0].acknowledgedAt);});
test('retention prunes expired audit and alerts without deleting accounts',t=>{const {db,operations,advance}=fixture(t);operations.audit('synthetic','usuario_creado');db.prepare("INSERT INTO users VALUES('id','synthetic','User','hash','editor',1,0)").run();advance(91*86400000);operations.prune(true);assert.equal(db.prepare('SELECT count(*) AS n FROM audit').get().n,0);assert.equal(operations.alerts().length,0);assert.equal(db.prepare('SELECT count(*) AS n FROM users').get().n,1);});
test('audit storage has a second row bound independent of time retention',t=>{const {db,operations}=fixture(t);operations.maxAuditRows=3;for(let i=0;i<6;i++)operations.audit('synthetic','event',String(i));operations.prune(true);assert.equal(db.prepare('SELECT count(*) n FROM audit').get().n,3);assert.equal(db.prepare('SELECT target_username FROM audit ORDER BY id').all()[0].target_username,'3');});
test('anonymization requires disabled account and removes identity from retained SQL records',t=>{const {db,operations}=fixture(t);db.prepare("INSERT INTO users VALUES('id','synthetic-person','User','hash','editor',1,0)").run();assert.throws(()=>operations.anonymizeDisabled('id','admin'),e=>e.status===409);db.exec("UPDATE users SET active=0 WHERE id='id'");operations.audit('synthetic-person','documento_guardado','synthetic-person');assert.equal(operations.anonymizeDisabled('id','admin').ok,true);const row=db.prepare('SELECT * FROM users').get();assert.equal(row.active,0);assert(row.username.startsWith('removed-'));assert(!JSON.stringify(db.prepare('SELECT * FROM audit').all()).includes('synthetic-person'));});
test('anonymization also removes MFA secrets and recovery codes',t=>{const {db,operations}=fixture(t);db.exec("CREATE TABLE mfa_secrets(user_id TEXT,encrypted TEXT); CREATE TABLE mfa_recovery(user_id TEXT,code_hash TEXT); INSERT INTO users VALUES('id','synthetic','User','hash','admin',0,0); INSERT INTO mfa_secrets VALUES('id','encrypted'); INSERT INTO mfa_recovery VALUES('id','hash');");operations.anonymizeDisabled('id','operator');assert.equal(db.prepare('SELECT count(*) n FROM mfa_secrets').get().n,0);assert.equal(db.prepare('SELECT count(*) n FROM mfa_recovery').get().n,0);});
